global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
    - targets:
      - prometheus_main:9090

  - job_name: nodes
    scrape_interval: 5s
    static_configs:
    - targets:
      - 54.202.44.234:9100
      - 54.202.140.50:9100
      - 52.26.142.167:9100

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - 54.202.44.234:8081
      - 54.202.140.50:8081
      - 54.202.140.50:8081

